### ISSUE TITLE
Merge new term mapping

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-CDS/EPND-FAIRification#21]
Pulling in main branch to sprint branch, and compare

**Comment by shashankmc** [comment]
@jvsoest Is a file under `templates/cedar/add.html` not pushed into the main branch? Getting an error when trying to add metadata entries.

**Comment by jvsoest** [comment]
@shashankmc ah, that's because the front-end cedar stuff is not yet built. 
If you run the file `management_webpage/cedar_embeddable_editor/build_frontend.sh` (go into the directory, and from there run the script), it will build the Angular project and store the `templates/cedar/add.html` file.

**Comment by jvsoest** [comment]
merge done
