### ISSUE TITLE
Mapping view does not take into account the CEDAR metadata

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-CDS/EPND-FAIRification#26]
The mapping view is now for all projects. Make sure the mapping only applies to one given cohort/CEDAR metadata object. otherwise mappings from different projects will overlap

Solution: take the cohort or dataset instance identifier in account when creating the graph of mapped data.
When using the latter, this will also solve #25

**Comment by shashankmc** [comment]
Column and cell mapping happens on two different graphs. Should that be continued or is it to be done on a single graph?

**Comment by shashankmc** [comment]
Single graph but for each uploaded dataset with a unique identifier.

**Comment by shashankmc** [comment]
The current pull request has everything distributed between two different graphs. Too dependent to change it with this PR. So creating a new issue and labeling it as enhancement.
