### ISSUE TITLE
GitLab registry: "HTTP Basic: Access denied. The provided password or token ..."

### ISSUE THREAD

**Issue by aiaragomes** [MaastrichtU-CDS/EPND-FAIRification#37]
Error when running `docker-compose up` for the first time:

```
$ docker-compose up -d
[+] Running 0/3
 ⠿ rdf-store Error                                                                                 0.7s
 ⠿ webui Error                                                                                     0.7s
 ⠿ triplifier Error                                                                                0.7s
Error response from daemon: Head "https://registry.gitlab.com/v2/um-cds/fair/tools/docker-graphdb/manifests/latest": unauthorized: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/user/profile/account/two_factor_authentication#troubleshooting
```

Current solution:
1. Create access token with `read_registry` scope
2. Run `docker login` to authenticate
    `$ docker login https://registry.gitlab.com -u <username> -p <token>`

Preferred solution:
Publish images to GitHub registry?

**Comment by shashankmc** [comment]
I think this might be a very system specific issue. I am unable to replicate it. We are also pushing it into github registry - https://github.com/MaastrichtU-CDS/EPND-FAIRification/blob/a42b9ba95699a1e635f8f861bf7a19aa9b819327/.github/workflows/github_actions.yaml#L11

**Comment by shashankmc** [comment]
Moving everything to github registry.

Current pending task is creating snapshot for [triplifier boot repo](https://github.com/MaastrichtU-CDS/triplifier-boot) and publishing that as a jar package.

**Comment by shashankmc** [comment]
Completed for triplifier boot repo as well.
