### ISSUE TITLE
Upload of SHACL fails

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-CDS/EPND-FAIRification#6]
Line: https://github.com/MaastrichtU-CDS/EPND-FAIRification/blob/791a5f5cb8cbdfaa170731bee8cb43ac66c4c348/management_webpage/development_endpoint/run.sh#L17

For some reason the cURL upload does fail. Possible causes:
- Comments in the SHACL file (hashtag), which is parsed but then giving errors
- Something else

We need to test which triples are being uploaded, and where the upload starts to fail. Manual upload into GraphDB does work (as a temporary workaround)

**Comment by shashankmc** [comment]
Removed the comments in the SHACL file and this was the result.

![Screenshot 2022-05-11 at 15 34 51](https://user-images.githubusercontent.com/3445114/167862581-23edfe8e-9461-4a00-bc48-1efb491d52d8.png)

**Comment by jvsoest** [comment]
That's the correct result :)

Ok, that means we have to insert a regular expression, I've tried it here on a local file (different computer, no docker etc.). Need to implement it in our shell script.

```
sed "s/#.*$//g" shacl.ttl > shacl_nocomment.ttl
```

**Comment by jvsoest** [comment]
Should be fixed in e88330e
